language: ruby
install: true
install_trash:
 - bundle install --gemfile=test/dummy/Gemfile
script:
 - cd test/dummy && bundle install --gemfile=./Gemfile --path vendor/bundle
 - RAILS_ENV=test bundle exec rspec spec -f documentation
